---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 8
    assignees:
      - "jlec"
  #   - package-ecosystem: "devcontainers"
  #     directory: "/"
  #     schedule:
  #       interval: "weekly"
  #     open-pull-requests-limit: 8
  #
  #     assignees:
  #       - "jlec"
  #
  #   - package-ecosystem: "docker"
  #     directory: "/"
  #     schedule:
  #       interval: "weekly"
  #     open-pull-requests-limit: 8
  #
  #     assignees:
  #       - "jlec"
  #
  #   - package-ecosystem: "docker-compose"
  #     directory: "/"
  #     schedule:
  #       interval: "weekly"
  #     open-pull-requests-limit: 8
  #
  #     assignees:
  #       - "jlec"
  #
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 8
    assignees:
      - "jlec"
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    registries: "*"
    open-pull-requests-limit: 8
    assignees:
      - "jlec"
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 8
    assignees:
      - "jlec"
  - package-ecosystem: "terraform"
    directory: "/deployment"
    schedule:
      interval: "weekly"
    registries: "*"
    open-pull-requests-limit: 8
    assignees:
      - "jlec"
registries:
  terraform-jlec:
    type: terraform-registry
    url: https://jlec.scalr.io/
    token: ${{ secrets.SCALR_TOKEN_DEPENDABOT }}
