[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]

[tool.black]
line-length = 128

[tool.commitizen]
name = "cz_conventional_commits"
tag_format = "v$version"
update_changelog_on_bump = true
version = "0.0.9"
version_files = [
  "Taskfile.yml",
  "VERSION",
  "pyproject.toml:version"
]

[tool.poetry]
authors = ["Justin Lecher <justin@jlec.de>"]
description = "sshkey TF provider"
license = "Apache-2.0"
name = "terraform_provider_sshkey"
version = "0.0.9"

[tool.poetry.dependencies]
ansible = "^7.1.0"
molecule = "^4.0.4"
netaddr = "^0"
pytest-testinfra = "^7.0.0"
python = "^3.10"
python-consul = "^1.1.0"

[tool.poetry.extras]
molecule = ["ansible", "docker", "lint"]
pytest-testinfra = ["ansible", "docker", "local"]

[tool.poetry.group.dev.dependencies]
black = "^22.12.0"
commitizen = "^2.39.1"
cruft = "^2.12.0"
isort = "^5.11.4"
poetry = "^1.3.1"
pre-commit = "^2.21.0"
pytest = "^7.2.0"
pytest-clarity = "^1.0.1"
pytest-cookies = "^0"
pytest-parallel = "^0"
pytest-xdist = "^3.1.0"
pyupgrade = "^3.3.1"
pyyaml = "^6.0"
yamllint = "^1.28.0"
