---
name: Continuous Delivery

# yamllint disable-line rule:truthy
on:
  # yamllint disable-line rule:empty-values
  workflow_dispatch:

  push:
    branches:
      - main

permissions: read-all

jobs:
  goreleaser:
    name: "GO Releaser"
    if: >-
      startsWith(github.event.head_commit.message, 'bump:')
    uses: jlec/github-actions/.github/workflows/reusable-cd-go.yml@main
    permissions:
      contents: write
      statuses: write
    secrets:
      pat: ${{ secrets.PAT_GITHUB_TOKEN }}
      token: ${{ secrets.GITHUB_TOKEN }}
      tfe_release_token: ${{ secrets.TFE_RELEASE_KEY }}
      gpg_release_key: ${{ secrets.GPG_RELEASE_KEY }}
